### ISSUE TITLE
pychattr installation time error on rpy2

### ISSUE THREAD

**Issue by asaeed9** [jmwoloso/pychattr#3]
I'm trying to install pychattr using `pip install pychattr` and getting parsing issue when it tries to install rpy2. I'm using 3.6.4 Python and R 3.4.1 version. I tried to install rpy2 using `pip install rpy2` but it gave me the same error. But, then I downloaded wheel for rpy2, could only find 2.9.5, and successfully installed it. However, I'm still unable to install pychattr because of rpy2 issue. Can you suggest some fix?

**Comment by jmwoloso** [comment]
Hi @asaeed9! Apologies for taking this long to respond. I was actively developing the project while I was at my last position and I started with a new company and haven't had much time to further the development of it. I seem to remember that I had to pin that specific version of rpy2 (2.9.4) because of a similar issue.

My goal this spring was to eliminate the reliance on R all together by porting the library over to a pure-python implementation, which for the most part is complete, but I still have some fine-tuning to do.

I'll try to get that wrapped up in the near-term and let you know when I make it available and/or you can follow the repo and be alerted when there are new releases.

**Comment by asaeed9** [comment]
Hi,

Thanks for your reply. I was really looking forward to something like this.
For reasons only known to IT, I had a terrible time convincing them to
allow R Installation. So, I am hoping Python version will be really useful.
please do let me know, if you need any help. I might be able to collaborate
with you on this. Thanks.

Regards,
Ahsan

**Comment by jmwoloso** [comment]
@asaeed9  Just released v0.2.0. Give it a shot and let me know if you have any issues.
